const Database = [
  {
    id: "ID001",
    name: "Samsung Galaxy Note10",
    manufacturer: "Samsung",
    price: "20000",
    country: "S.Korea",
  },
  {
    id: "ID002",
    name: "iPhone 11 Pro",
    manufacturer: "Apple",
    price: "25000",
    country: "USA",
  },
  {
    id: "ID003",
    name: "Sony Xperia XZ3",
    manufacturer: "Sony",
    price: "24000",
    country: "Japan",
  },
  {
    id: "ID004",
    name: "Samsung Galaxy S20 Ultra",
    manufacturer: "Samsung",
    price: "22500",
    country: "S.Korea",
  },
  {
    id: "ID005",
    name: "LG Velvet 5G",
    manufacturer: "LG",
    price: "21500",
    country: "S.Korea",
  },
  {
    id: "ID006",
    name: "Oppo Find X 2",
    manufacturer: "Oppo",
    price: "18000",
    country: "China",
  },
  {
    id: "ID007",
    name: "Vsmart Active 3",
    manufacturer: "Vsmart",
    price: "5500",
    country: "Vietnam",
  },
  {
    id: "ID008",
    name: "iPhone XR",
    manufacturer: "Apple",
    price: "15000",
    country: "USA",
  },
  {
    id: "ID009",
    name: "Samsung Galaxy Fold",
    manufacturer: "Samsung",
    price: "40000",
    country: "Korea",
  },
  {
    id: "ID010",
    name: "Samsung Galaxy Note20",
    manufacturer: "Samsung",
    price: "25000",
    country: "Korea",
  },
  {
    id: "ID011",
    name: "Samsung Galaxy Note9",
    manufacturer: "Samsung",
    price: "17000",
    country: "S.Korea",
  },
];
export default Database;
